a2/a2/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from tabel import views
urlpatterns = [
    url(r'^$', views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^formpage/', views.formview, name='form1'),
    url(r'^tabel/', include('tabel.urls')),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'^special/$',views.special,name='special'),
]

a2/tabel/urls.py
from django.conf.urls import url
from . import views

app_name='tabel'
urlpatterns = [
url(r'^$', views.index, name='index'),
url(r'^register/$', views.register, name='register'),
url(r'^user_login/$',views.user_login,name='user_login')
]

a2/tabel/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User)

    portofolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

class Pekerjaan(models.Model):
    name= models.CharField(max_length=100)

    def __str__(self):
        return self.name


class daftartabel(models.Model):
    nama = models.CharField(max_length=500)
    usia = models.CharField( max_length=100)
    alamat = models.CharField( max_length=1000)
    pekerjaan = models.ForeignKey(Pekerjaan, on_delete=models.CASCADE)

    def __str__(self):
        return self.nama +' - '+ self.usia +' - '+ self.alamat

a2/tabel/forms.py
from django import forms
from django.core import validators
from django.contrib.auth.models import User
from .models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portofolio_site','profile_pic')

class form1(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.EmailField()
    verifyemail = forms.EmailField(label='enter your email again')
    text = forms.CharField(widget=forms.Textarea)

    def clean(self):
        all_clean_data = super().clean()
        email = all_clean_data['email']
        vemail = all_clean_data['verifyemail']

        if email != vemail:
            raise forms.ValidationError('make sure you your email match!')

class form2(forms.Form):
    name = forms.CharField(max_length=100)

a2/tabel/views.py
from django.http import HttpResponseRedirect, HttpResponse
from .models import daftartabel, Pekerjaan
from .forms import form1, form2, UserForm, UserProfileInfoForm
from django.template import loader
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User


def index(request):
    if request.method == 'POST':
        #print(request.POST['name'])
        current_name=request.POST['name']
        all_datas = daftartabel.objects.filter(pekerjaan_id=request.POST['name'])
    else:
        all_datas = daftartabel.objects.all()

    all_pekerjaan = Pekerjaan.objects.all()
    template = loader.get_template('tabel/index.html')
    if request.method == 'POST':
        context = {
            'all_datas' : all_datas,
            'all_pekerjaan' : all_pekerjaan,
            'current_name' : int(request.POST['name']),
            }
    else:
                context = {
                    'all_datas' : all_datas,
                    'all_pekerjaan' : all_pekerjaan,
                    }
    return HttpResponse(template.render(context, request))

@login_required
def special(request):
    return HttpResponse("You're logged in, Nice !")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False
    if request.method =="POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'tabel/registration.html',
                            {'user_form':user_form,
                             'profile_form':profile_form,
                             'registered':registered})



def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
        print(user)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("Account not Active")
        else:
            print("Someone tried to login and failed!")
            print("Username: {} and password {}".format(username,password))
            return HttpResponse("Invalid Login details supplied")
    else:
        return render(request,'tabel/login.html',{})


def formview(request):
    form = forms.form1()

    if request.method == 'POST':
        form= forms.form1(request.POST)
        if form.is_valid():
            print("Validation Complete")
            print("Name : "+form.cleaned_data['name'])
            print("E-mail : "+form.cleaned_data['email'])
            print("Text : "+form.cleaned_data['text'])



    return render(request,'tabel/formpage.html',{'form':form})

a2/templates/tabel/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title_block %}
      Base
    {% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

  </head>
  <body>
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <ul class="nav navbar-nav">
      <li><a class="navbar-brand" href="{url 'tabel:index'}">DJANGO</a></li>
      <li><a class="navbar-link" href="{%url 'admin:index'%}">Admin</a></li>
      <li><a class="navbar-link" href="{% url 'tabel:register'%}">Register</a></li>

      {% if user.is_authenticated %}
      <li><a class='navbar-link' href="{% url 'logout' %}">Logout</a></li>
      {% else %}
      <li><a class='navbar-link' href="{% url 'tabel:user_login' %}">Login</a></li>
      {% endif %}
    </ul>
  </div>
</nav>

    <div class="container">
      {% block body_block %}

      {% endblock %}
  </body>
</html>

a2/templates/tabel/formpage.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    <title>formpage</title>
  </head>
  <body>
    <div class="container">
    <h2> Please Fill Out Your Form :</h2>
  <form method="post">
    {{form.as_p}}
    {% csrf_token %}
    <input type="submit" class="btn btn-success" value="Submit">
  </form>
  </body>
</html>

a2/templates/tabel/index.html
{% extends "tabel/base.html" %}
{% block body_block %}


  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

<div class="container-fluid">
<div class="jumbotron">

  <h3> Cari Pekerjaan : </h3>

<form  method="post">

<select name="name">

<option >--SELECT--</option>
  {% for job in all_pekerjaan%}
  <option value="{{ job.id }}" {% if current_name == job.id %}selected {% endif %}>
                 {{ job.name }}
     </option>
    {% endfor %}
    </select>
{% csrf_token %}

  <input type="submit" class="btn btn-success" value="submit" >
</form>
  <table class="table">
<p>{{current_name}}</p>
<p>     {{ forloop.counter }}</p>
    <div class="thead">
      <tr>
        <th> Nama</th>
        <th>Usia</th>
        <th>Alamat</th>
        <th>Pekerjaan</th>
      </tr>
    </div>
    {% for data in all_datas%}
      <tr>
        <td>{{ data.nama}}</td>
        <td>{{ data.usia}}</td>
        <td>{{ data.alamat}}</td>
        <td>{{ data.pekerjaan}}</td>
      </tr>

    </div>
        {% endfor %}
  </table>
</div>
  {% endblock %}

a2/templates/tabel/login.html
{% extends "tabel/base.html" %}
{% block body_block %}
  <div class="jumbotron">
    <h1> Please Login</h1>
    <form action="{% url 'tabel:user_login'%}" method="post">
      {% csrf_token %}
      <label for="username"> Username : </label>
      <input type="text" name="username" placeholder="Enter Username">

      <label for="password"> Password : </label>
      <input type="password" name="password">

      <input type="submit" name="" value="Login">
    </form>
  </div>
{% endblock %}

a2/templates/tabel/registration.html
{% extends "tabel/base.html" %}
{% load staticfiles %}
{% block body_block %}
  <div class="jumbotron">
    {% if registered %}
      <h1>Thank You for Registering</h1>
    {% else %}
      <h1>Register Here!</h1>
      <h3>Fill out The Form</h3>
      <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" name="" value="Register">
      </form>
    {%endif%}

  </div>
{% endblock %}